services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sandbox-backend-dev
    ports:
      - "5050:5050"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - sandbox_network
    environment:
      - DOCKER_ENV=true

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sandbox-rabbitmq-dev
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      sandbox_network:
        aliases:
          - rabbitmq

volumes:
  rabbitmq_data:

networks:
  sandbox_network:
    driver: bridge