services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandbox-backend
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./node_modules:/app/node_modules
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      app-network:
        aliases:
          - backend
    environment:
      - DOCKER_ENV=true




  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sandbox-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    restart: unless-stopped
    networks:
      app-network:
        aliases:
          - rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  node_modules:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge