services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sandbox-backend-dev
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./logs:/app/logs
      - node_modules:/app/node_modules
    command: yarn dev
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sandbox-rabbitmq-dev
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    restart: unless-stopped
    networks:
      - app-network

volumes:
  node_modules:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge