services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandbox-backend
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  node_modules: